export const SET_CITIES = "SET_CITIES";
export const SET_LOCATION = "SET_LOCATION";
export const SET_5DAYS = "SET_5DAYS";
export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";